### PR TITLE
removed = char from password generation as this is not valid in sql connection strings

### PR DESCRIPTION
**Pull request by george-onebeyond**
char is invalid for sql server connection strings

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by george-onebeyond — COMMENTED** [review]
changed

**Comment by nickskliar-davies** [comment]
FYI @george-onebeyond the "suggested" comment is auto-created by github. You don't actually need all that text in your description. A short "I deleted this because it doesn't work" would actually be fine!!!

**Review by nickskliar-davies — APPROVED** [review]

**Comment by george-onebeyond** [comment]
Hi Nick

Thanks, good to know.

Now I have permission do you want me to create a new branch for this as the update I made is just for my fork.

thanks

**Comment by nickskliar-davies** [comment]
Um, that looks like a PR from your fork. It _seems_ fine. Let's see what happens if I merge....

**Pull request merged**
